=== koonut/2247221/lab3.xsd
<?xml version="1.0"?>  
<xs:schema xmlns="urn:schemas-microsoft-com:xml-data" xmlns:dt="urn:schemas-microsoft-com:datatypes">  
  
<xs:element name="pet_store">
    <xs:element name="pet">  
        <xs:complexType>  
        <xs:sequence>  
            <xs:element name="name" type="xs:string"/>  
            <xs:element name="breed" type="xs:string"/>  
            <xs:element name="discription" type="xs:string"/>  
            <xs:element name="age" type="xs:number"/>  
            <xs:element name="quantity" type="xs:number"/>  
            <xs:element name="price" type="xs:string"/>
            <xs:element name="availability" type="xs:string"/>  
            <xs:element name="store" type="xs:string"/>
        </xs:sequence>  
        </xs:complexType>  
    </xs:element>
</xs:element>  
  
</xs:schema>

=== koonut/2247221/lab3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="lab3.xsl"?>
<pet_store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="lab3.xsd">
    <pet>
        <name>egg</name>
        <breed>dog</breed>
        <discription>golden</discription>
        <age>3</age>
        <quantity>4</quantity>
        <price>7000</price>
        <availability>available</availability>
        <store>XYZ</store>
    </pet>
    <pet>
        <name>lucky</name>
        <breed>dog</breed>
        <discription>labrador</discription>
        <age>1</age>
        <quantity>10</quantity>
        <price>8000</price>
        <availability>available</availability>
        <store>ZYX</store>
    </pet>
    <pet>
        <name>vicky</name>
        <breed>dog</breed>
        <discription>labrador</discription>
        <age>3</age>
        <quantity>2</quantity>
        <price>4000</price>
        <availability>non-available</availability>
        <store>ZYX</store>
    </pet>

</pet_store>
